version: '3'

services:
  filebeat:
    build:
      context: filebeat/
    volumes:
      - /var/lib/docker/containers:/usr/share/dockerlogs/data
      - /var/run/docker.sock
    networks:
      - elk

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: elastic
      discovery.type: single-node
    networks:
      - elk
 
  logstash:
    build:
      context: logstash/
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
  
  kibana:
    build:
      context: kibana/
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

volumes:
  elasticsearch:

networks: 
  elk:
    driver: bridge
